name: minigpt4
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - cudatoolkit
  - pip
  - pip:
    - torch==2.0.0
    - torchaudio
    - torchvision
    - huggingface-hub==0.18.0
    - matplotlib==3.7.0
    - psutil==5.9.4
    - iopath
    - pyyaml==6.0
    - regex==2022.10.31
    - tokenizers==0.13.2
    - tqdm==4.64.1
    - transformers==4.30.0
    - timm==0.6.13
    - webdataset==0.2.48
    - omegaconf==2.3.0
    - opencv-python==4.7.0.72
    - decord==0.6.0
    - peft==0.2.0
    - sentence-transformers
    - gradio==3.47.1
    - accelerate==0.20.3
    - bitsandbytes==0.37.0
    - wandb
